version: '3.8'
services:
  mysqldb:
    image: mysql:8.1.0
    restart: always
    environment:
      MYSQL_DATABASE: 'logisticsDB'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
  api:
    container_name: api
    image: logistics-api
    build:
      context: ./
      dockerfile: docker/Dockerfile
    depends_on:
      - mysqldb
    ports:
      - "8080:8080"
    restart: always

volumes:
  my-db:
